In [10]:
import pandas as pd
import numpy as np
from sklearn import datasets, linear_model
from sklearn.model_selection import train_test_split
from matplotlib import pyplot as plt
from sklearn.datasets import make_regression
from keras.models import Sequential
from keras.optimizers import SGD
from matplotlib import pyplot
from sklearn.preprocessing import StandardScaler
from numpy import array
from numpy import reshape
from keras.layers import Activation, Dense,Dropout

Using TensorFlow backend.


In [2]:
df = pd.read_csv("titanic_train.csv")

In [3]:
df.head(5)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [6]:
df.describe()


PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [8]:
df.isnull().any()

PassengerId    False
Survived       False
Pclass         False
Name           False
Sex            False
Age             True
SibSp          False
Parch          False
Ticket         False
Fare           False
Cabin           True
Embarked        True
dtype: bool

In [9]:
df.shape

(891, 12)

In [10]:
df.isnull()

PassengerId  Survived  Pclass   Name    Sex    Age  SibSp  Parch  Ticket  \
0          False     False   False  False  False  False  False  False   False   
1          False     False   False  False  False  False  False  False   False   
2          False     False   False  False  False  False  False  False   False   
3          False     False   False  False  False  False  False  False   False   
4          False     False   False  False  False  False  False  False   False   
..           ...       ...     ...    ...    ...    ...    ...    ...     ...   
886        False     False   False  False  False  False  False  False   False   
887        False     False   False  False  False  False  False  False   False   
888        False     False   False  False  False   True  False  False   False   
889        False     False   False  False  False  False  False  False   False   
890        False     False   False  False  False  False  False  False   False   

      Fare  Cabin  Embarked  
0    False   True     False  
1    False  False     False  
2    False   True     False  
3    False  False     False  
4    False   True     False  
..     ...    ...       ...  
886  False   True     False  
887  False  False     False  
888  False   True     False  
889  False  False     False  
890  False   True     False  

[891 rows x 12 columns]

In [13]:
print("Arun"+ " "+"Chapagain")

Arun Chapagain


In [15]:
# List
list = [1,2,3]


In [16]:
list

[1, 2, 3]

In [19]:
list[2]

3

In [22]:
list[:-1]

[1, 2]

In [23]:
list[::-1]

[3, 2, 1]

In [24]:
#tuple immutable
tuple = (1,2,3,4,5)

In [25]:
tuple

(1, 2, 3, 4, 5)

In [26]:
#dicetionary
dict = {
    "name": "Arun",
    "sex":"male"
}

In [27]:
dict

{'name': 'Arun', 'sex': 'male'}

In [28]:
dict["location"]="Pharping"

In [29]:
dict

{'name': 'Arun', 'sex': 'male', 'location': 'Pharping'}

In [30]:
dict.items()

dict_items([('name', 'Arun'), ('sex', 'male'), ('location', 'Pharping')])

In [31]:
dict.keys()

dict_keys(['name', 'sex', 'location'])

In [32]:
dict.values()

dict_values(['Arun', 'male', 'Pharping'])

In [33]:
for key, value in dict.items():
    print(key,value)

name Arun
sex male
location Pharping


In [34]:
def func():
    print("No arg")
    
func()
    

No arg


In [36]:
def func1(arg="Yes"):
    print(arg)

func1()

Yes


In [41]:
#String Formatting
num = int(input("Enter a number"))

if num % 2 ==0:
    print(f"{num} is even")
else:
    print(f"{num} is odd")

Enter a number5
5 is odd


In [42]:
print(f"square of {num} is {num **2}")

square of 5 is 25


In [45]:
class Class1():
    def __init__(self):
        self.id = 1
        self.name = "John"
        
    def show(self):
        print(f"Name :{self.name} Id:{self.id}")
        
obj1 = Class1()
obj1.show()

Name :John Id:1


In [54]:
class Class2(Class1):
    
    
    def show(self):
        print("Name",self.name)
        print("Id",self.id)
        
a = Class2()
a.show()

Name John
Id 1


In [55]:
class Person:
  def __init__(self, fname, lname):
    self.firstname = fname
    self.lastname = lname

  def printname(self):
    print(self.firstname, self.lastname)

class Student(Person):
  def __init__(self, fname, lname, year):
    super().__init__(fname, lname)
    self.graduationyear = year

x = Student("Mike", "Olsen", 2019)
print(x.graduationyear)


2019


In [5]:
from evenodd import even_odd as oe
# Restart kernel after this


In [6]:
x = oe(2)

Even


In [7]:
# numpy allows us to use array
# Numerical Pytho


In [11]:
np.__version__#To check version
#Shift + TAB to read the documentation
#TAB shows available functions


'1.17.2'

In [13]:
array1 = np.array([1,2,3,4])

In [14]:
array1

array([1, 2, 3, 4])

In [19]:
zeros = np.zeros([5,5])
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [20]:
ones = np.ones([5,5])
ones
ones.shape

(5, 5)

In [24]:
zeros.reshape(1,25) #this is 2D

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [25]:
zeros.reshape(25)#This is 1D

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0.])

In [27]:
zeros.reshape(25,-1)

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [28]:
zeros.reshape(1,-25)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [29]:
repeat = np.repeat(10,100)

In [30]:
repeat

array([10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10,
       10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10, 10])

In [31]:
repeat.reshape(10,10)

array([[10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10, 10, 10, 10, 10, 10]])

In [32]:
repeat.reshape(-1,5)

array([[10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10],
       [10, 10, 10, 10, 10]])

In [34]:
sums = np.sum(repeat)
sums

1000

In [ ]:
sums = np.sum(repeat)
sums

In [36]:
mean =np.mean(repeat)

In [37]:
mean

10.0

In [38]:
list = [1,2,3,4,5,6]
array2 = np.array(list)

In [39]:
type(array2)

numpy.ndarray

In [40]:
list **2

TypeError: unsupported operand type(s) for ** or pow(): 'list' and 'int'

In [41]:
array2**2

array([ 1,  4,  9, 16, 25, 36])

In [42]:
np.pi #Value of pi

3.141592653589793

In [54]:
#Random Number
random = np.random.randn(5,5,4,1,5)
random


array([[[[[ 5.36224543e-01,  1.58535435e+00,  2.84581693e-01,
            2.02248303e+00, -1.09700070e+00]],

         [[ 1.51777200e+00, -1.88371619e-01,  1.00355969e-02,
            1.27176773e+00,  1.62174738e-01]],

         [[-1.45856917e-01, -1.06342759e+00,  3.47688061e-01,
           -9.75560668e-01, -1.89240999e+00]],

         [[-1.17672234e-01, -5.36635897e-01,  3.47583249e-01,
           -6.46946759e-01,  6.79679701e-01]]],


        [[[-1.26978751e-01,  2.20681287e+00, -6.96115325e-01,
            5.64360658e-01, -1.58841277e+00]],

         [[ 1.78156561e+00,  3.30969489e-01,  8.61509315e-01,
           -3.03536454e-01,  2.69879667e-01]],

         [[-1.33045957e-02,  5.98790925e-01, -8.83815705e-01,
            6.77614550e-01, -9.54091926e-01]],

         [[-1.86637907e+00,  4.56533410e-02, -9.55208725e-01,
            4.89904744e-01,  1.60575121e+00]]],


        [[[-1.40991592e+00,  1.76060769e+00,  6.01730388e-01,
           -1.09693236e+00, -1.56598911e+00]],

      

In [ ]:
# # generate random integer values
# from random import seed
# from random import randint
# # seed random number generator
# seed(1)
# # generate some integers
# for _ in range(10):
#     value = randint(0, 10)
#     print(value)

In [62]:
from collections import Counter


In [83]:
integers = np.random.randint(5,5000,500)
integers

array([2559, 1264, 3402, 3226, 4118,  932, 2248, 4295, 3024, 1306,  877,
       4719, 4669, 4651,  101, 1972, 4677, 4977, 4643, 1457, 3580, 3723,
       1937, 1926, 2901, 1586, 1627,  135, 1545,  433, 3864,  708, 1177,
       4065, 1810,  166, 2452, 4772, 1053,  185, 1362, 3134,  270, 2219,
       2395,  567,  141, 2343, 3987,  618, 4282, 2954, 2771,  439, 2729,
       2957,  941, 4480, 3016, 2148, 2438,  570, 3705, 4496,  365, 2201,
       3069, 3221, 1881, 1119, 2943, 2239, 4869, 1966, 2975, 3919, 1902,
       2417,    5, 1818,  858, 1060,  874, 3484, 2745,  610, 2386, 2918,
       1650, 3987, 1708,  802, 3400, 2534, 2703, 3017, 3049, 3342, 1725,
        876, 4133, 3838,  155,  740,  668, 1488, 4212, 3078, 3276, 4187,
       2802,   86,  117, 1812,   88, 2516, 1708, 4812,   55, 3629, 3546,
         57, 2027, 4479, 1763, 1902, 2684,  643, 3499, 4659, 1778,    8,
       2627, 4253, 3372, 3625, 1715,  972,  738, 2041, 4667, 2577, 3035,
       4466, 3073, 2925, 3031, 1660, 2294, 3827, 33

In [84]:
counts = Counter(integers)

In [85]:
counts

Counter({2559: 1,
         1264: 1,
         3402: 1,
         3226: 1,
         4118: 1,
         932: 1,
         2248: 1,
         4295: 1,
         3024: 1,
         1306: 1,
         877: 1,
         4719: 1,
         4669: 1,
         4651: 1,
         101: 1,
         1972: 1,
         4677: 1,
         4977: 1,
         4643: 1,
         1457: 1,
         3580: 1,
         3723: 1,
         1937: 1,
         1926: 1,
         2901: 1,
         1586: 1,
         1627: 1,
         135: 1,
         1545: 1,
         433: 2,
         3864: 1,
         708: 1,
         1177: 1,
         4065: 1,
         1810: 1,
         166: 1,
         2452: 1,
         4772: 1,
         1053: 1,
         185: 1,
         1362: 1,
         3134: 1,
         270: 1,
         2219: 1,
         2395: 1,
         567: 1,
         141: 1,
         2343: 1,
         3987: 2,
         618: 2,
         4282: 1,
         2954: 1,
         2771: 1,
         439: 1,
         2729: 1,
         2957: 1,
     

In [86]:
len(counts)

479

In [87]:
# List
l1 = []
l1.append(1)

In [88]:
l1

[1]

In [89]:
del l1[0]

In [90]:
l1


[]

In [91]:

l1 = [1,2,3,4,[1,2,3]]

In [92]:
l1

[1, 2, 3, 4, [1, 2, 3]]

In [95]:
# Tuple
t1= (1,2,3)


t1

In [96]:
t1

(1, 2, 3)

In [97]:
# Tuple cannot be edited
# Original data change nahos bhanera tuple banainxa


In [102]:
# dictionary
d1 = {}
d1[1]="Nepal"
d1[2]="china"

In [103]:
d1

{1: 'Nepal', 2: 'china'}

In [112]:
d1.keys()

dict_keys([1, 2])

In [110]:
l1 = [1,2,3,4,5,6]
l1 = np.array(l1,dtype = np.float)

In [111]:
l1

array([1., 2., 3., 4., 5., 6.])